package net.bytebutcher.burpsendtoextension.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import net.bytebutcher.burpsendtoextension.models.placeholder.behaviour.CommandSeparatedPlaceholderBehaviour;
import net.bytebutcher.burpsendtoextension.models.placeholder.behaviour.PlaceholderBehaviour;
import net.bytebutcher.burpsendtoextension.models.placeholder.behaviour.StringSeparatedPlaceholderBehaviour;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class SendToAddAdvancedPlaceholderBehaviourPanel extends JPanel {

    private JTextField txtSeparator;
    private JPanel pnlMain;
    private JComboBox cmbSeperator;
    private JLabel lblPlaceholder;

    public SendToAddAdvancedPlaceholderBehaviourPanel(StringSeparatedPlaceholderBehaviour placeholderBehaviour) {
        this.add(pnlMain);
        initFields(placeholderBehaviour);
        initEventListener();
    }

    public SendToAddAdvancedPlaceholderBehaviourPanel(CommandSeparatedPlaceholderBehaviour placeholderBehaviour) {
        this.add(pnlMain);
        initFields(placeholderBehaviour);
        initEventListener();
    }

    private void initFields(StringSeparatedPlaceholderBehaviour placeholderBehaviour) {
        this.lblPlaceholder.setText(placeholderBehaviour.getPlaceholder());
        this.txtSeparator.setText(placeholderBehaviour.getSeparator());
        this.txtSeparator.setEnabled(true);
        this.cmbSeperator.setSelectedIndex(0);
    }

    private void initFields(CommandSeparatedPlaceholderBehaviour placeholderBehaviour) {
        this.lblPlaceholder.setText(placeholderBehaviour.getPlaceholder());
        this.txtSeparator.setText("");
        this.txtSeparator.setEnabled(false);
        this.cmbSeperator.setSelectedIndex(1);
    }

    private void initEventListener() {
        this.cmbSeperator.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (cmbSeperator.getSelectedIndex() == 0) {
                    txtSeparator.setEnabled(true);
                    txtSeparator.setText("");
                } else {
                    txtSeparator.setEnabled(false);
                    txtSeparator.setText("");
                }
            }
        });
    }

    public PlaceholderBehaviour getPlaceholderBehaviour() {
        if (cmbSeperator.getSelectedIndex() == 0) {
            return new StringSeparatedPlaceholderBehaviour(lblPlaceholder.getText(), txtSeparator.getText());
        } else {
            return new CommandSeparatedPlaceholderBehaviour(lblPlaceholder.getText());
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pnlMain = new JPanel();
        pnlMain.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        txtSeparator = new JTextField();
        pnlMain.add(txtSeparator, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        cmbSeperator = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("separated by string");
        defaultComboBoxModel1.addElement("split into separate commands");
        cmbSeperator.setModel(defaultComboBoxModel1);
        pnlMain.add(cmbSeperator, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblPlaceholder = new JLabel();
        lblPlaceholder.setText("...");
        pnlMain.add(lblPlaceholder, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }

}
